### ISSUE TITLE
Problem for enable_..=False solvers/basic.py

### ISSUE THREAD

**Issue by asgerbolet** [gautelinga/BERNAISE#7]
The basic solver Crashes when enable_NS, enable_EC and enable_PF is set to False (One at a time) due to variabols that are not defined! see setup function especilaly line 119 -138 (solvers/basic.py) 
Futher there is a problem in line 284-294 (solvers/basic.py) when calling the solver

**Comment by asgerbolet** [comment]
from terminal:
bolet@kaoslx09:~/git/BERNAISE$ python sauce.py solver=basic enable_NS=false
Welcome to the simple problem!
Creating folders.
Traceback (most recent call last):
  File "sauce.py", line 154, in <module>
    vars().update(setup(**vars()))
  File "/home/bolet/git/BERNAISE/solvers/basic.py", line 126, in setup
    phi_1, u_1, M_1, c_1, V_1,
UnboundLocalError: local variable 'u_1' referenced before assignment
Aborted (core dumped)
.

So stile not working??

**Comment by gautelinga** [comment]
I think this was fixed a while back.
