### ISSUE TITLE
Periodic mesh genration 

### ISSUE THREAD

**Issue by asgerbolet** [gautelinga/BERNAISE#8]
how do i make the mesh for rounde barbell periodic, and way is Snausen/Snoevsen periodic?

**Comment by gautelinga** [comment]
Snoevsen is periodic almost by chance, I think. I think it has to do with the fact that mshr first adds the boundary nodes, that the geometry it is symmetric, and that mshr doesn't need to add any Steiner points to the boundary. But with this thinking, the barbell should also be periodic?
